### ISSUE TITLE
How to get the Pred mask of PVN3D on YCB-Video dataset?

### ISSUE THREAD

**Issue by ZJU-PLP** [Gorilla-Lab-SCUT/BiCo-Net#3]
Dear author:

   Could you mind sharing the **method or details** to generate Pred mask of PVN3D on YCB-Video dataset?
   Currently, I can only get the Pred mask of PVN3D on YCB-Video dataset from your provided website link. However, I cannot find the details of Pred mask of PVN3D on YCB-Video dataset in your paper.

**Comment by aragakiyui611** [comment]
You might need to wait for few days as the author is busy working now.

**Comment by ZJU-PLP** [comment]
@aragakiyui611 Okk, thanks for your reply. I am looking forward to your newly notice.

**Comment by ZJU-PLP** [comment]
@aragakiyui611 Hi, could you mind sharing the details of this problem if you are leisure?

**Comment by aragakiyui611** [comment]
Here I reply you briefly, run the inference of [PVN3D](https://github.com/ethnhe/PVN3D) and project the point cloud to image space coordinate and fill the corresponding pixel with predicted segmentation class id, then you get the mask.

**Comment by ZJU-PLP** [comment]
@aragakiyui611 Thanks for your reply. I still cannot understand how to run the **inference** of [PVN3D](https://github.com/ethnhe/PVN3D). Could you mind sharing more details?

Another question, how to plot Figure 3 (Figure 3: Comparative evaluation with different levels of occlusion on the YCB-Video benchmark) in your paper? I have looked up to **DenseFusion** but I could not find details. Could you mind sharing the details to plot Figure 3 in terms of different levels of occlusion on the YCB-Video benchmark?

**Comment by aragakiyui611** [comment]
1. Go to run test of PVN3D
2. please refer to the supplementary materials of DenseFusion

**Comment by ZJU-PLP** [comment]
@aragakiyui611 
1. Ok, I will have a try.
2. Thanks for providing the details. Furthermore, could you mind sharing the script if it is possible?

**Comment by aragakiyui611** [comment]
[occ_percent.zip](https://github.com/Gorilla-Lab-SCUT/BiCo-Net/files/9734123/occ_percent.zip)
please check the zip for plotting. Usually such files are not provided.

**Comment by ZJU-PLP** [comment]
> [occ_percent.zip](https://github.com/Gorilla-Lab-SCUT/BiCo-Net/files/9734123/occ_percent.zip) please check the zip for plotting. Usually such files are not provided. The codes are not arranged and thus a little mixed.

Ok, thanks a lot!
